import * as b from "./builders";
import type { CatalogEntry, Category, Dims, Params } from "./types";

/**
 * The generic catalogue. No brand data: realistic standard sizes only.
 * Each row: id, Dutch and English name, size in cm, builder and options.
 */

type Opts = Partial<Omit<CatalogEntry, "id" | "name" | "category" | "size" | "build">>;

const WOOD = "#8B6A4E";
const OAK = "#B8916A";
const LINEN = "#E9E2D3";
const SAGE = "#87A08C";
const SAGE_DARK = "#4D6857";
const CREAM = "#F5F1E8";
const GREIGE = "#A9A58B";
const BRASS = "#B08D57";
const DARK = "#4A3526";
const CHARCOAL = "#4B4A46";
const WHITE = "#F7F5F0";
const TERRACOTTA = "#B9714F";

const FABRICS = [LINEN, SAGE, GREIGE, "#C9B8A0", "#7A8B99", "#B56B5A", CHARCOAL, "#E3EAE2"];

function scaleDims(s: Dims, f: number): Dims {
  return { w: Math.round(s.w * f), d: Math.round(s.d * f), h: Math.round(s.h * f) };
}

function entry(
  id: string,
  nl: string,
  en: string,
  category: Category,
  size: [number, number, number],
  build: (d: Dims, p: Params) => ReturnType<CatalogEntry["build"]>,
  opts: Opts = {},
): CatalogEntry {
  const dims = { w: size[0], d: size[1], h: size[2] };
  return {
    id,
    name: { nl, en },
    category,
    tags: [],
    size: dims,
    min: opts.min ?? scaleDims(dims, 0.6),
    max: opts.max ?? scaleDims(dims, 1.6),
    shape: "rect",
    layer: "furniture",
    mount: "floor",
    colors: { main: LINEN, second: LINEN },
    ...opts,
    build,
  };
}

const seat = (o: Opts = {}): Opts => ({ againstWall: true, palette: FABRICS, ...o });

// ------------------------------------------------------------------ seating (32)
const seating: CatalogEntry[] = [
  entry(
    "sofa-2",
    "Bank 2-zits",
    "Sofa 2-seater",
    "seating",
    [170, 90, 85],
    b.sofa,
    seat({ params: { seats: 2 }, tags: ["bank", "sofa"] }),
  ),
  entry(
    "sofa-3",
    "Bank 3-zits",
    "Sofa 3-seater",
    "seating",
    [220, 95, 85],
    b.sofa,
    seat({ params: { seats: 3 }, tags: ["bank", "sofa"], colors: { main: SAGE, second: SAGE } }),
  ),
  entry(
    "sofa-4",
    "Bank 4-zits",
    "Sofa 4-seater",
    "seating",
    [280, 100, 85],
    b.sofa,
    seat({ params: { seats: 4 }, tags: ["bank", "sofa"] }),
  ),
  entry(
    "sofa-round-arms",
    "Bank ronde armleuningen",
    "Sofa with rolled arms",
    "seating",
    [210, 92, 82],
    b.sofa,
    seat({ params: { seats: 3, arms: "round" } }),
  ),
  entry(
    "sofa-armless",
    "Bank zonder armleuning",
    "Armless sofa",
    "seating",
    [180, 90, 80],
    b.sofa,
    seat({ params: { seats: 2, arms: "none" } }),
  ),
  entry(
    "sofa-floor",
    "Lage loungebank",
    "Low lounge sofa",
    "seating",
    [240, 105, 70],
    b.sofa,
    seat({ params: { seats: 3, floor: true } }),
  ),
  entry(
    "sofa-chesterfield",
    "Chesterfield",
    "Chesterfield",
    "seating",
    [220, 95, 75],
    b.sofa,
    seat({
      params: { seats: 3, arms: "round", tufted: true },
      colors: { main: "#6B3F2A", second: "#6B3F2A" },
    }),
  ),
  entry(
    "sofa-chaise-left",
    "Bank met chaise links",
    "Sofa with chaise, left",
    "seating",
    [260, 160, 85],
    b.sofa,
    seat({ params: { seats: 3, chaise: "left" } }),
  ),
  entry(
    "sofa-chaise-right",
    "Bank met chaise rechts",
    "Sofa with chaise, right",
    "seating",
    [260, 160, 85],
    b.sofa,
    seat({ params: { seats: 3, chaise: "right" } }),
  ),
  entry(
    "sofa-corner-left",
    "Hoekbank links",
    "Corner sofa, left",
    "seating",
    [270, 220, 85],
    b.cornerSofa,
    seat({ params: { side: "left" }, tags: ["hoek", "corner"] }),
  ),
  entry(
    "sofa-corner-right",
    "Hoekbank rechts",
    "Corner sofa, right",
    "seating",
    [270, 220, 85],
    b.cornerSofa,
    seat({ params: { side: "right" }, tags: ["hoek", "corner"] }),
  ),
  entry(
    "sofa-u",
    "U-bank",
    "U-shaped sofa",
    "seating",
    [320, 220, 85],
    b.cornerSofa,
    seat({ params: { u: true } }),
  ),
  entry(
    "sofabed-closed",
    "Slaapbank (dicht)",
    "Sofa bed (closed)",
    "seating",
    [200, 95, 85],
    b.sofa,
    seat({ params: { seats: 3 }, tags: ["slaapbank"] }),
  ),
  entry(
    "sofabed-open",
    "Slaapbank (open)",
    "Sofa bed (open)",
    "seating",
    [200, 210, 85],
    b.sofa,
    seat({ params: { seats: 3, bed: true }, tags: ["slaapbank"] }),
  ),
  entry(
    "loveseat",
    "Loveseat",
    "Loveseat",
    "seating",
    [140, 85, 85],
    b.sofa,
    seat({ params: { seats: 2, arms: "round" } }),
  ),
  entry(
    "armchair",
    "Fauteuil",
    "Armchair",
    "seating",
    [80, 85, 90],
    b.armchair,
    seat({ colors: { main: GREIGE, second: GREIGE } }),
  ),
  entry(
    "armchair-round",
    "Fauteuil rond",
    "Armchair, rolled arms",
    "seating",
    [85, 85, 85],
    b.armchair,
    seat({ params: { arms: "round" } }),
  ),
  entry(
    "armchair-wingback",
    "Oorfauteuil",
    "Wingback chair",
    "seating",
    [80, 85, 110],
    b.armchair,
    seat({ params: { style: "wingback" }, colors: { main: SAGE_DARK, second: SAGE_DARK } }),
  ),
  entry(
    "armchair-lounge",
    "Loungestoel",
    "Lounge chair",
    "seating",
    [85, 90, 75],
    b.armchair,
    seat({ params: { arms: "none" } }),
  ),
  entry("pouf-round", "Poef rond", "Round pouf", "seating", [50, 50, 42], b.pouf, {
    shape: "round",
    palette: FABRICS,
  }),
  entry("pouf-square", "Poef vierkant", "Square pouf", "seating", [55, 55, 42], b.pouf, {
    params: { shape: "square" },
    palette: FABRICS,
  }),
  entry("ottoman", "Hocker", "Ottoman", "seating", [90, 60, 42], b.pouf, {
    params: { shape: "square" },
    palette: FABRICS,
  }),
  entry("stool", "Krukje", "Stool", "seating", [35, 35, 45], b.stool, {
    shape: "round",
    colors: { main: OAK, second: OAK },
  }),
  entry("stool-bar", "Barkruk", "Bar stool", "seating", [40, 40, 75], b.stool, {
    shape: "round",
    params: { bar: true },
    colors: { main: DARK, second: DARK },
  }),
  entry("stool-counter", "Keukenkruk", "Counter stool", "seating", [40, 40, 65], b.stool, {
    shape: "round",
    params: { bar: true },
  }),
  entry("bench", "Bankje", "Bench", "seating", [120, 35, 45], b.bench, {
    colors: { main: OAK, second: LINEN },
  }),
  entry(
    "bench-cushion",
    "Bankje met kussen",
    "Bench with cushion",
    "seating",
    [120, 40, 47],
    b.bench,
    { params: { cushion: true }, colors: { main: OAK, second: SAGE } },
  ),
  entry(
    "bench-hall",
    "Halbankje met rugleuning",
    "Hall bench with back",
    "seating",
    [100, 40, 85],
    b.bench,
    { params: { back: true }, againstWall: true },
  ),
  entry("hanging-chair", "Hangstoel", "Hanging chair", "seating", [100, 100, 195], b.hangingChair, {
    shape: "round",
    colors: { main: "#C9B08A", second: CREAM },
  }),
  entry(
    "chaise-longue",
    "Chaise longue",
    "Chaise longue",
    "seating",
    [65, 165, 80],
    b.chaiseLongue,
    { colors: { main: GREIGE, second: CREAM } },
  ),
  entry("beanbag", "Zitzak", "Beanbag", "seating", [80, 80, 70], b.pouf, {
    shape: "round",
    palette: FABRICS,
  }),
  entry("rocking-chair", "Schommelstoel", "Rocking chair", "seating", [65, 85, 100], b.chair, {
    params: { style: "spindle", arms: true },
    colors: { main: WOOD, second: WOOD },
  }),
];

// --------------------------------------------------------------- tables (24)
const chairStyle = (style: string, nl: string, en: string, extra: Opts = {}) =>
  entry(`chair-${style}`, nl, en, "tables", [45, 50, 85], b.chair, {
    params: { style },
    colors: { main: OAK, second: LINEN },
    tags: ["stoel", "chair"],
    ...extra,
  });

const tables: CatalogEntry[] = [
  entry("dining-4", "Eettafel 4 personen", "Dining table, 4", "tables", [140, 85, 75], b.table, {
    colors: { main: OAK, second: OAK },
    tags: ["eettafel"],
    surface: 1,
  }),
  entry("dining-6", "Eettafel 6 personen", "Dining table, 6", "tables", [180, 90, 75], b.table, {
    colors: { main: OAK, second: OAK },
    tags: ["eettafel"],
    surface: 1,
  }),
  entry("dining-8", "Eettafel 8 personen", "Dining table, 8", "tables", [240, 100, 75], b.table, {
    params: { base: "trestle" },
    colors: { main: OAK, second: DARK },
    surface: 1,
  }),
  entry(
    "dining-10",
    "Eettafel 10 personen",
    "Dining table, 10",
    "tables",
    [300, 105, 75],
    b.table,
    { params: { base: "trestle" }, colors: { main: WOOD, second: DARK }, surface: 1 },
  ),
  entry("dining-round", "Eettafel rond", "Round dining table", "tables", [120, 120, 75], b.table, {
    shape: "round",
    params: { shape: "round", base: "pedestal" },
    colors: { main: BRASS, second: DARK },
    surface: 1,
  }),
  entry("dining-oval", "Eettafel ovaal", "Oval dining table", "tables", [200, 100, 75], b.table, {
    shape: "round",
    params: { shape: "oval" },
    colors: { main: OAK, second: OAK },
    surface: 1,
  }),
  entry(
    "dining-extendable",
    "Uitschuifbare eettafel",
    "Extendable dining table",
    "tables",
    [160, 90, 75],
    b.table,
    {
      params: { extendable: true },
      max: { w: 280, d: 110, h: 80 },
      colors: { main: OAK, second: OAK },
      surface: 1,
    },
  ),
  entry("coffee-table", "Salontafel", "Coffee table", "tables", [110, 60, 45], b.table, {
    colors: { main: DARK, second: DARK },
    surface: 1,
    params: { shelf: true },
  }),
  entry(
    "coffee-table-round",
    "Salontafel rond",
    "Round coffee table",
    "tables",
    [80, 80, 40],
    b.table,
    {
      shape: "round",
      params: { shape: "round", base: "pedestal" },
      colors: { main: OAK, second: OAK },
      surface: 1,
    },
  ),
  entry(
    "coffee-table-oval",
    "Salontafel ovaal",
    "Oval coffee table",
    "tables",
    [120, 65, 38],
    b.table,
    { shape: "round", params: { shape: "oval" }, surface: 1, colors: { main: CREAM, second: OAK } },
  ),
  entry("side-table", "Bijzettafel", "Side table", "tables", [45, 45, 55], b.table, {
    surface: 1,
    colors: { main: OAK, second: OAK },
  }),
  entry(
    "side-table-round",
    "Bijzettafel rond",
    "Round side table",
    "tables",
    [45, 45, 55],
    b.table,
    {
      shape: "round",
      params: { shape: "round", base: "pedestal" },
      surface: 1,
      colors: { main: BRASS, second: BRASS },
    },
  ),
  entry("console", "Wandtafel", "Console table", "tables", [120, 35, 80], b.table, {
    againstWall: true,
    surface: 1,
    params: { drawer: true },
    colors: { main: WOOD, second: WOOD },
  }),
  entry("bar-table", "Bartafel", "Bar table", "tables", [70, 70, 105], b.table, {
    shape: "round",
    params: { shape: "round", base: "pedestal" },
    surface: 1,
    colors: { main: DARK, second: CHARCOAL },
  }),
  chairStyle("classic", "Stoel klassiek", "Classic chair"),
  chairStyle("windsor", "Windsorstoel", "Windsor chair", { colors: { main: WOOD, second: WOOD } }),
  chairStyle("scandi", "Stoel Scandinavisch", "Scandinavian chair", {
    colors: { main: "#D8C3A5", second: "#D8C3A5" },
  }),
  chairStyle("upholstered", "Gestoffeerde stoel", "Upholstered chair", {
    colors: { main: OAK, second: SAGE },
    palette: FABRICS,
  }),
  chairStyle("bistro", "Bistrostoel", "Bistro chair", {
    colors: { main: CHARCOAL, second: CHARCOAL },
  }),
  chairStyle("industrial", "Industriële stoel", "Industrial chair", {
    colors: { main: CHARCOAL, second: CHARCOAL },
  }),
  chairStyle("tulip", "Tulpstoel", "Tulip chair", {
    shape: "round",
    colors: { main: WHITE, second: WHITE },
  }),
  entry(
    "chair-arms",
    "Stoel met armleuning",
    "Armchair (dining)",
    "tables",
    [55, 55, 85],
    b.chair,
    { params: { style: "upholstered", arms: true }, colors: { main: OAK, second: GREIGE } },
  ),
  entry("dining-bench", "Eettafelbank", "Dining bench", "tables", [160, 38, 46], b.bench, {
    colors: { main: OAK, second: OAK },
  }),
  entry(
    "dining-bench-back",
    "Eettafelbank met rugleuning",
    "Dining bench with back",
    "tables",
    [160, 45, 85],
    b.bench,
    { params: { back: true, cushion: true }, colors: { main: OAK, second: LINEN } },
  ),
];

// -------------------------------------------------------------- bedroom (22)
const bedEntry = (w: number, extra: Opts = {}) =>
  entry(`bed-${w}`, `Bed ${w}x200`, `Bed ${w}x200`, "bedroom", [w, 210, 90], b.bed, {
    againstWall: true,
    colors: { main: OAK, second: "#E3EAE2" },
    palette: FABRICS,
    tags: ["bed"],
    ...extra,
  });

const bedroom: CatalogEntry[] = [
  bedEntry(80),
  bedEntry(90),
  bedEntry(120),
  bedEntry(140),
  bedEntry(160),
  bedEntry(180),
  bedEntry(200),
  entry(
    "bed-boxspring-160",
    "Boxspring 160x200",
    "Box spring 160x200",
    "bedroom",
    [160, 210, 120],
    b.bed,
    { againstWall: true, params: { kind: "boxspring" }, colors: { main: GREIGE, second: CREAM } },
  ),
  entry(
    "bed-boxspring-180",
    "Boxspring 180x200",
    "Box spring 180x200",
    "bedroom",
    [180, 210, 120],
    b.bed,
    { againstWall: true, params: { kind: "boxspring" }, colors: { main: CHARCOAL, second: WHITE } },
  ),
  entry("bed-canopy", "Hemelbed", "Canopy bed", "bedroom", [160, 210, 200], b.bed, {
    againstWall: true,
    params: { kind: "canopy" },
    colors: { main: WOOD, second: CREAM },
  }),
  entry("bed-bunk", "Stapelbed", "Bunk bed", "bedroom", [100, 210, 165], b.bed, {
    againstWall: true,
    params: { kind: "bunk" },
    colors: { main: OAK, second: SAGE },
  }),
  entry("bed-storage", "Opbergbed", "Storage bed", "bedroom", [160, 210, 95], b.bed, {
    againstWall: true,
    params: { kind: "storage" },
    colors: { main: OAK, second: LINEN },
  }),
  entry("crib", "Babybedje", "Cot", "bedroom", [65, 125, 90], b.cabinet, {
    params: { doors: 0, legs: true },
    colors: { main: WHITE, second: WHITE },
  }),
  entry("nightstand", "Nachtkastje", "Nightstand", "bedroom", [45, 40, 50], b.cabinet, {
    againstWall: true,
    surface: 1,
    params: { doors: 0, drawers: 2, legs: true },
    colors: { main: OAK, second: OAK },
  }),
  entry(
    "nightstand-open",
    "Nachtkastje open",
    "Open nightstand",
    "bedroom",
    [40, 35, 55],
    b.shelves,
    {
      againstWall: true,
      surface: 1,
      params: { shelves: 2, open: true },
      colors: { main: WOOD, second: WOOD },
    },
  ),
  entry(
    "wardrobe-hinged-2",
    "Kledingkast 2 deuren",
    "Wardrobe, 2 doors",
    "bedroom",
    [100, 60, 220],
    b.cabinet,
    {
      againstWall: true,
      params: { doors: 2 },
      colors: { main: CREAM, second: CREAM },
      tags: ["kast"],
    },
  ),
  entry(
    "wardrobe-hinged-3",
    "Kledingkast 3 deuren",
    "Wardrobe, 3 doors",
    "bedroom",
    [150, 60, 220],
    b.cabinet,
    {
      againstWall: true,
      params: { doors: 3 },
      colors: { main: CREAM, second: CREAM },
      tags: ["kast"],
    },
  ),
  entry(
    "wardrobe-sliding",
    "Schuifdeurkast",
    "Sliding wardrobe",
    "bedroom",
    [200, 65, 236],
    b.cabinet,
    {
      againstWall: true,
      params: { doors: 2, sliding: true },
      colors: { main: WHITE, second: GREIGE },
      tags: ["kast"],
    },
  ),
  entry("dresser", "Commode", "Chest of drawers", "bedroom", [100, 50, 85], b.cabinet, {
    againstWall: true,
    surface: 1,
    params: { doors: 0, drawers: 4 },
    colors: { main: WOOD, second: WOOD },
  }),
  entry("dresser-tall", "Ladekast hoog", "Tall chest", "bedroom", [60, 48, 125], b.cabinet, {
    againstWall: true,
    surface: 1,
    params: { doors: 0, drawers: 6 },
    colors: { main: WHITE, second: WHITE },
  }),
  entry("vanity-table", "Kaptafel", "Dressing table", "bedroom", [100, 45, 76], b.desk, {
    againstWall: true,
    surface: 1,
    params: { drawers: true },
    colors: { main: CREAM, second: BRASS },
  }),
  entry("blanket-chest", "Dekenkist", "Blanket chest", "bedroom", [100, 45, 48], b.cabinet, {
    surface: 1,
    params: { doors: 0, drawers: 0 },
    colors: { main: WOOD, second: WOOD },
  }),
];

// ---------------------------------------------------------------- office (16)
const office: CatalogEntry[] = [
  entry("desk-100", "Bureau 100", "Desk 100", "office", [100, 55, 75], b.desk, {
    againstWall: true,
    surface: 1,
    colors: { main: OAK, second: CHARCOAL },
  }),
  entry("desk-140", "Bureau 140", "Desk 140", "office", [140, 70, 75], b.desk, {
    againstWall: true,
    surface: 1,
    colors: { main: OAK, second: CHARCOAL },
  }),
  entry("desk-180", "Bureau 180", "Desk 180", "office", [180, 80, 75], b.desk, {
    againstWall: true,
    surface: 1,
    colors: { main: WHITE, second: CHARCOAL },
  }),
  entry("desk-240", "Duo-bureau 240", "Double desk 240", "office", [240, 80, 75], b.desk, {
    againstWall: true,
    surface: 1,
    colors: { main: OAK, second: CHARCOAL },
    tags: ["naast elkaar", "side by side"],
  }),
  entry("desk-corner", "Hoekbureau", "Corner desk", "office", [160, 140, 75], b.desk, {
    againstWall: true,
    surface: 1,
    params: { corner: true },
    colors: { main: WHITE, second: CHARCOAL },
  }),
  entry("desk-standing", "Zit-sta-bureau", "Sit-stand desk", "office", [160, 80, 75], b.desk, {
    againstWall: true,
    surface: 1,
    params: { standing: true },
    max: { w: 200, d: 90, h: 125 },
    colors: { main: OAK, second: CHARCOAL },
  }),
  entry("desk-drawers", "Bureau met laden", "Desk with drawers", "office", [140, 65, 75], b.desk, {
    againstWall: true,
    surface: 1,
    params: { drawers: true },
    colors: { main: WOOD, second: WOOD },
  }),
  entry("secretary", "Secretaire", "Secretary desk", "office", [90, 45, 110], b.cabinet, {
    againstWall: true,
    params: { doors: 2, drawers: 2 },
    colors: { main: DARK, second: DARK },
  }),
  entry("office-chair", "Bureaustoel", "Office chair", "office", [65, 65, 110], b.officeChair, {
    shape: "round",
    colors: { main: CHARCOAL, second: CHARCOAL },
  }),
  entry(
    "office-chair-light",
    "Bureaustoel licht",
    "Office chair, light",
    "office",
    [62, 62, 100],
    b.officeChair,
    { shape: "round", colors: { main: GREIGE, second: GREIGE } },
  ),
  entry("monitor-24", 'Monitor 24"', 'Monitor 24"', "office", [55, 20, 45], b.monitor, {
    mount: "stack",
    layer: "decor",
  }),
  entry("monitor-32", 'Monitor 32"', 'Monitor 32"', "office", [72, 22, 55], b.monitor, {
    mount: "stack",
    layer: "decor",
  }),
  entry("laptop", "Laptop", "Laptop", "office", [33, 23, 22], b.laptop, {
    mount: "stack",
    layer: "decor",
  }),
  entry("printer", "Printer", "Printer", "office", [45, 40, 25], b.printer, {
    mount: "stack",
    layer: "decor",
    colors: { main: CHARCOAL, second: CHARCOAL },
  }),
  entry("filing-cabinet", "Ladeblok", "Filing cabinet", "office", [42, 55, 60], b.cabinet, {
    surface: 1,
    params: { doors: 0, drawers: 3 },
    colors: { main: WHITE, second: WHITE },
  }),
  entry("office-shelf", "Archiefrek", "Office shelving", "office", [80, 35, 180], b.shelves, {
    againstWall: true,
    params: { shelves: 5, books: true },
    colors: { main: WHITE, second: SAGE },
  }),
];

// --------------------------------------------------------------- storage (26)
const storage: CatalogEntry[] = [
  entry("bookcase", "Boekenkast", "Bookcase", "storage", [80, 30, 200], b.shelves, {
    againstWall: true,
    params: { books: true },
    colors: { main: WHITE, second: TERRACOTTA },
    tags: ["kast"],
  }),
  entry(
    "bookcase-wide",
    "Boekenkast breed",
    "Wide bookcase",
    "storage",
    [160, 35, 200],
    b.shelves,
    { againstWall: true, params: { books: true }, colors: { main: OAK, second: SAGE_DARK } },
  ),
  entry("bookcase-low", "Boekenkast laag", "Low bookcase", "storage", [120, 30, 90], b.shelves, {
    againstWall: true,
    surface: 1,
    params: { shelves: 2, books: true },
    colors: { main: OAK, second: BRASS },
  }),
  entry("open-shelf", "Open kast", "Open shelving", "storage", [80, 35, 180], b.shelves, {
    params: { open: true },
    colors: { main: OAK, second: OAK },
  }),
  entry("vitrine", "Vitrinekast", "Display cabinet", "storage", [90, 40, 190], b.cabinet, {
    againstWall: true,
    params: { doors: 2, glass: true },
    colors: { main: DARK, second: DARK },
  }),
  entry("sideboard", "Dressoir", "Sideboard", "storage", [180, 45, 80], b.cabinet, {
    againstWall: true,
    surface: 1,
    params: { doors: 3, legs: true },
    colors: { main: WOOD, second: WOOD },
  }),
  entry("sideboard-low", "Dressoir laag", "Low sideboard", "storage", [200, 45, 60], b.cabinet, {
    againstWall: true,
    surface: 1,
    params: { doors: 4, legs: true },
    colors: { main: OAK, second: OAK },
  }),
  entry("buffet", "Buffetkast", "Buffet cabinet", "storage", [130, 50, 200], b.cabinet, {
    againstWall: true,
    params: { doors: 2, drawers: 2, glass: true },
    colors: { main: SAGE, second: SAGE },
  }),
  entry("tv-unit", "Tv-meubel", "TV unit", "storage", [180, 45, 50], b.cabinet, {
    againstWall: true,
    surface: 1,
    params: { doors: 2, drawers: 1 },
    colors: { main: DARK, second: DARK },
  }),
  entry(
    "tv-unit-wall",
    "Zwevend tv-meubel",
    "Floating TV unit",
    "storage",
    [180, 40, 35],
    b.cabinet,
    {
      againstWall: true,
      surface: 1,
      mount: "wall",
      elevation: 30,
      params: { doors: 2 },
      colors: { main: WHITE, second: WHITE },
    },
  ),
  entry("shoe-cabinet", "Schoenenkast", "Shoe cabinet", "storage", [80, 30, 100], b.cabinet, {
    againstWall: true,
    surface: 1,
    params: { doors: 2 },
    colors: { main: WHITE, second: WHITE },
  }),
  entry("coat-rack", "Kapstok staand", "Coat stand", "storage", [50, 50, 180], b.coatRack, {
    shape: "round",
  }),
  entry("coat-rack-wall", "Kapstok wand", "Wall coat rack", "storage", [90, 12, 40], b.coatRack, {
    mount: "wall",
    elevation: 150,
    params: { wall: true },
  }),
  entry(
    "cabinet-wall-modular",
    "Kastenwand modulair",
    "Modular wall unit",
    "storage",
    [240, 40, 220],
    b.shelves,
    {
      againstWall: true,
      params: { shelves: 6, books: true },
      max: { w: 600, d: 60, h: 300 },
      colors: { main: CREAM, second: GREIGE },
    },
  ),
  entry("cabinet-high", "Hoge kast", "Tall cabinet", "storage", [60, 40, 200], b.cabinet, {
    againstWall: true,
    params: { doors: 1 },
    colors: { main: WHITE, second: WHITE },
  }),
  entry("cabinet-low", "Lage kast", "Low cabinet", "storage", [80, 40, 80], b.cabinet, {
    againstWall: true,
    surface: 1,
    params: { doors: 2 },
    colors: { main: CREAM, second: CREAM },
  }),
  entry("linen-cupboard", "Linnenkast", "Linen cupboard", "storage", [120, 55, 210], b.cabinet, {
    againstWall: true,
    params: { doors: 2, drawers: 2 },
    colors: { main: "#DCE4DB", second: "#DCE4DB" },
  }),
  entry("storage-bench", "Opbergbank", "Storage bench", "storage", [100, 40, 45], b.cabinet, {
    againstWall: true,
    surface: 1,
    params: { doors: 0, drawers: 1 },
    colors: { main: OAK, second: OAK },
  }),
  entry("ladder-shelf", "Ladderrek", "Ladder shelf", "storage", [60, 35, 180], b.shelves, {
    againstWall: true,
    params: { shelves: 4, open: true },
    colors: { main: OAK, second: OAK },
  }),
  entry("wine-rack", "Wijnrek", "Wine rack", "storage", [60, 30, 100], b.shelves, {
    againstWall: true,
    params: { shelves: 6 },
    colors: { main: WOOD, second: WOOD },
  }),
  entry("wall-shelf-60", "Wandplank 60", "Wall shelf 60", "storage", [60, 20, 4], b.wallShelf, {
    mount: "wall",
    elevation: 140,
    surface: 1,
    colors: { main: OAK, second: OAK },
  }),
  entry("wall-shelf-120", "Wandplank 120", "Wall shelf 120", "storage", [120, 22, 4], b.wallShelf, {
    mount: "wall",
    elevation: 140,
    surface: 1,
    colors: { main: OAK, second: OAK },
  }),
  entry("wall-cabinet", "Hangkast", "Wall cabinet", "storage", [80, 30, 60], b.cabinet, {
    mount: "wall",
    elevation: 140,
    params: { doors: 2 },
    colors: { main: WHITE, second: WHITE },
  }),
  entry(
    "wall-unit-floating",
    "Zwevend wandmeubel",
    "Floating wall unit",
    "storage",
    [120, 35, 40],
    b.cabinet,
    {
      mount: "wall",
      elevation: 40,
      surface: 1,
      params: { doors: 0, drawers: 1 },
      colors: { main: OAK, second: OAK },
    },
  ),
  entry("storage-boxes", "Opbergmanden", "Storage baskets", "storage", [80, 35, 30], b.basket, {
    colors: { main: "#C9B08A", second: CREAM },
  }),
  entry("umbrella-stand", "Paraplubak", "Umbrella stand", "storage", [25, 25, 50], b.vase, {
    shape: "round",
    colors: { main: CHARCOAL, second: CHARCOAL },
  }),
];

// --------------------------------------------- kitchen and bathroom (30)
const kitchenUnit = (
  id: string,
  nl: string,
  en: string,
  w: number,
  kind: string,
  extra: Opts = {},
) =>
  entry(id, nl, en, "kitchen", [w, 60, 90], b.kitchenUnit, {
    againstWall: true,
    surface: 1,
    params: { kind },
    colors: { main: SAGE, second: "#D9D4C7" },
    tags: ["keuken"],
    ...extra,
  });

const kitchenBath: CatalogEntry[] = [
  kitchenUnit("kitchen-base-40", "Onderkast 40", "Base cabinet 40", 40, "base"),
  kitchenUnit("kitchen-base-60", "Onderkast 60", "Base cabinet 60", 60, "base"),
  kitchenUnit("kitchen-base-80", "Onderkast 80", "Base cabinet 80", 80, "base"),
  kitchenUnit("kitchen-corner", "Hoekkast", "Corner cabinet", 90, "base"),
  kitchenUnit("kitchen-sink", "Spoelkast", "Sink cabinet", 80, "sink"),
  kitchenUnit("kitchen-hob", "Kookplaatkast", "Hob cabinet", 60, "hob"),
  entry(
    "kitchen-wall-60",
    "Bovenkast 60",
    "Wall cabinet 60",
    "kitchen",
    [60, 35, 70],
    b.kitchenUnit,
    {
      mount: "wall",
      elevation: 145,
      params: { kind: "wall" },
      colors: { main: SAGE, second: SAGE },
    },
  ),
  entry(
    "kitchen-wall-80",
    "Bovenkast 80",
    "Wall cabinet 80",
    "kitchen",
    [80, 35, 70],
    b.kitchenUnit,
    {
      mount: "wall",
      elevation: 145,
      params: { kind: "wall" },
      colors: { main: SAGE, second: SAGE },
    },
  ),
  entry(
    "kitchen-tall",
    "Hoge keukenkast",
    "Tall kitchen unit",
    "kitchen",
    [60, 60, 210],
    b.cabinet,
    { againstWall: true, params: { doors: 1 }, colors: { main: SAGE, second: SAGE } },
  ),
  entry(
    "kitchen-island",
    "Kookeiland",
    "Kitchen island",
    "kitchen",
    [200, 100, 90],
    b.kitchenUnit,
    { surface: 1, params: { kind: "island" }, colors: { main: SAGE_DARK, second: "#D9D4C7" } },
  ),
  entry(
    "kitchen-island-small",
    "Keukeneiland klein",
    "Small kitchen island",
    "kitchen",
    [120, 70, 90],
    b.kitchenUnit,
    { surface: 1, params: { kind: "island" }, colors: { main: OAK, second: WHITE } },
  ),
  entry("fridge", "Koelkast", "Fridge", "kitchen", [60, 65, 185], b.appliance, {
    againstWall: true,
    params: { kind: "fridge" },
    colors: { main: WHITE, second: WHITE },
  }),
  entry(
    "fridge-american",
    "Amerikaanse koelkast",
    "American fridge",
    "kitchen",
    [90, 70, 180],
    b.appliance,
    { againstWall: true, params: { kind: "fridge" }, colors: { main: "#C8C8C4", second: WHITE } },
  ),
  entry("dishwasher", "Vaatwasser", "Dishwasher", "kitchen", [60, 58, 85], b.appliance, {
    againstWall: true,
    params: { kind: "dishwasher" },
  }),
  entry("oven", "Oven (inbouw)", "Built-in oven", "kitchen", [60, 56, 60], b.appliance, {
    againstWall: true,
    params: { kind: "oven" },
  }),
  entry("microwave", "Magnetron", "Microwave", "kitchen", [50, 38, 30], b.appliance, {
    mount: "stack",
    layer: "decor",
    params: { kind: "microwave" },
  }),
  entry("washer", "Wasmachine", "Washing machine", "bathroom", [60, 60, 85], b.appliance, {
    againstWall: true,
    surface: 1,
    params: { kind: "washer" },
  }),
  entry("dryer", "Droger", "Dryer", "bathroom", [60, 60, 85], b.appliance, {
    againstWall: true,
    surface: 1,
    params: { kind: "dryer" },
  }),
  entry("vanity-60", "Badmeubel 60", "Vanity 60", "bathroom", [60, 46, 85], b.vanity, {
    againstWall: true,
    colors: { main: OAK, second: WHITE },
    tags: ["badkamer"],
  }),
  entry("vanity-100", "Badmeubel 100", "Vanity 100", "bathroom", [100, 46, 85], b.vanity, {
    againstWall: true,
    colors: { main: SAGE_DARK, second: WHITE },
    tags: ["badkamer"],
  }),
  entry("vanity-double", "Dubbel badmeubel", "Double vanity", "bathroom", [140, 48, 85], b.vanity, {
    againstWall: true,
    colors: { main: WHITE, second: WHITE },
  }),
  entry("basin-pedestal", "Wastafel op zuil", "Pedestal basin", "bathroom", [55, 45, 85], b.basin, {
    againstWall: true,
  }),
  entry("basin-small", "Fonteintje", "Hand basin", "bathroom", [40, 25, 85], b.basin, {
    againstWall: true,
  }),
  entry("shower-90", "Douche 90x90", "Shower 90x90", "bathroom", [90, 90, 200], b.shower, {
    againstWall: true,
  }),
  entry("shower-walkin", "Inloopdouche", "Walk-in shower", "bathroom", [120, 90, 200], b.shower, {
    againstWall: true,
    params: { walkin: true },
  }),
  entry("bathtub", "Ligbad", "Bathtub", "bathroom", [170, 75, 58], b.bathtub, {
    againstWall: true,
  }),
  entry(
    "bathtub-freestanding",
    "Vrijstaand bad",
    "Freestanding bath",
    "bathroom",
    [170, 80, 62],
    b.bathtub,
    { shape: "round", params: { freestanding: true } },
  ),
  entry("toilet", "Toilet staand", "Floor toilet", "bathroom", [38, 68, 80], b.toilet, {
    againstWall: true,
  }),
  entry("toilet-wall", "Hangtoilet", "Wall-hung toilet", "bathroom", [36, 54, 100], b.toilet, {
    againstWall: true,
    params: { wall: true },
  }),
  entry(
    "towel-radiator",
    "Handdoekradiator",
    "Towel radiator",
    "bathroom",
    [50, 10, 120],
    b.shelves,
    {
      mount: "wall",
      elevation: 20,
      params: { shelves: 8, open: true },
      colors: { main: WHITE, second: WHITE },
    },
  ),
  entry("marker-water", "Wateraansluiting", "Water connection", "bathroom", [10, 10, 3], b.marker, {
    shape: "round",
    layer: "electrical",
    params: { kind: "water" },
    tags: ["aansluiting", "installatie"],
  }),
  entry("marker-drain", "Afvoer", "Drain", "bathroom", [10, 10, 3], b.marker, {
    shape: "round",
    layer: "electrical",
    params: { kind: "drain" },
    tags: ["aansluiting", "installatie"],
  }),
];

// ----------------------------------------------------------------- plants (13)
const plantEntry = (
  kind: string,
  nl: string,
  en: string,
  size: [number, number, number],
  extra: Opts = {},
) =>
  entry(`plant-${kind}`, nl, en, "plants", size, b.plant, {
    shape: "round",
    layer: "decor",
    params: { kind },
    colors: { main: TERRACOTTA, second: TERRACOTTA },
    palette: [TERRACOTTA, WHITE, CHARCOAL, "#C9B08A", SAGE],
    tags: ["plant"],
    ...extra,
  });

const plants: CatalogEntry[] = [
  plantEntry("monstera", "Monstera", "Monstera", [70, 70, 120]),
  plantEntry("ficus", "Ficus", "Ficus", [60, 60, 160]),
  plantEntry("olive", "Olijfboompje", "Olive tree", [70, 70, 170]),
  plantEntry("palm", "Palm", "Palm", [80, 80, 180]),
  plantEntry("fiddle", "Vioolbladplant", "Fiddle-leaf fig", [60, 60, 170]),
  plantEntry("snake", "Vrouwentong", "Snake plant", [35, 35, 80]),
  plantEntry("cactus", "Cactus", "Cactus", [30, 30, 90]),
  plantEntry("fern", "Varen", "Fern", [50, 50, 60]),
  plantEntry("pothos", "Klimop (pothos)", "Pothos", [40, 40, 50], { mount: "stack" }),
  plantEntry("bamboo", "Bamboe", "Bamboo", [50, 50, 190]),
  plantEntry("orchid", "Orchidee", "Orchid", [20, 20, 55], { mount: "stack" }),
  plantEntry("succulent", "Vetplantje", "Succulent", [15, 15, 15], { mount: "stack" }),
  plantEntry("hanging", "Hangplant", "Hanging plant", [40, 40, 70], {
    mount: "wall",
    elevation: 150,
  }),
];

// --------------------------------------------------------- decor and textiles (44)
const small = (o: Opts): Opts => ({ mount: "stack", layer: "decor", ...o });
const onWall = (elevation: number, o: Opts = {}): Opts => ({
  mount: "wall",
  layer: "decor",
  elevation,
  ...o,
});

const decor: CatalogEntry[] = [
  entry(
    "vase-small",
    "Vaas klein",
    "Small vase",
    "decor",
    [12, 12, 22],
    b.vase,
    small({ shape: "round", colors: { main: SAGE, second: SAGE } }),
  ),
  entry(
    "vase-tall",
    "Vaas hoog",
    "Tall vase",
    "decor",
    [18, 18, 45],
    b.vase,
    small({ shape: "round", colors: { main: CREAM, second: CREAM } }),
  ),
  entry("vase-floor", "Vloervaas", "Floor vase", "decor", [35, 35, 80], b.vase, {
    shape: "round",
    layer: "decor",
    colors: { main: TERRACOTTA, second: TERRACOTTA },
  }),
  entry(
    "flowers",
    "Bos bloemen",
    "Bunch of flowers",
    "decor",
    [20, 20, 45],
    b.vase,
    small({
      shape: "round",
      params: { flowers: true },
      colors: { main: "#DCE9EC", second: "#E8A9A0" },
    }),
  ),
  entry(
    "flowers-dried",
    "Droogbloemen",
    "Dried flowers",
    "decor",
    [22, 22, 60],
    b.vase,
    small({
      shape: "round",
      params: { flowers: true },
      colors: { main: TERRACOTTA, second: "#D8C3A5" },
    }),
  ),
  entry(
    "candle",
    "Kaars",
    "Candle",
    "decor",
    [8, 8, 20],
    b.candles,
    small({ shape: "round", colors: { main: CREAM, second: CREAM } }),
  ),
  entry(
    "candles-3",
    "Kaarsen (3)",
    "Candles (3)",
    "decor",
    [25, 8, 25],
    b.candles,
    small({ params: { count: 3 }, colors: { main: CREAM, second: CREAM } }),
  ),
  entry(
    "candlestick",
    "Kandelaar",
    "Candlestick",
    "decor",
    [12, 12, 35],
    b.candles,
    small({ shape: "round", colors: { main: BRASS, second: BRASS } }),
  ),
  entry(
    "books-row",
    "Boeken",
    "Books",
    "decor",
    [30, 20, 24],
    b.books,
    small({ params: { count: 8 }, colors: { main: SAGE_DARK, second: TERRACOTTA } }),
  ),
  entry(
    "books-stack",
    "Stapel boeken",
    "Stack of books",
    "decor",
    [28, 20, 12],
    b.books,
    small({ params: { count: 4, stack: true }, colors: { main: CREAM, second: GREIGE } }),
  ),
  entry(
    "bowl",
    "Schaal",
    "Bowl",
    "decor",
    [30, 30, 8],
    b.bowl,
    small({ shape: "round", colors: { main: OAK, second: OAK } }),
  ),
  entry(
    "fruit-bowl",
    "Fruitschaal",
    "Fruit bowl",
    "decor",
    [30, 30, 12],
    b.bowl,
    small({ shape: "round", params: { fruit: true }, colors: { main: WHITE, second: "#E0A33E" } }),
  ),
  entry(
    "tray",
    "Dienblad",
    "Tray",
    "decor",
    [45, 30, 3],
    b.generic,
    small({ colors: { main: BRASS, second: BRASS } }),
  ),
  entry(
    "sculpture",
    "Beeldje",
    "Sculpture",
    "decor",
    [15, 15, 30],
    b.sculpture,
    small({ colors: { main: CREAM, second: CREAM } }),
  ),
  entry(
    "clock",
    "Klok",
    "Clock",
    "decor",
    [35, 4, 35],
    b.clock,
    onWall(160, { shape: "round", colors: { main: DARK, second: WHITE } }),
  ),
  entry(
    "painting-small",
    "Schilderij klein",
    "Small painting",
    "decor",
    [40, 3, 50],
    b.frame,
    onWall(140, { colors: { main: "#C2A68B", second: DARK } }),
  ),
  entry(
    "painting-medium",
    "Schilderij",
    "Painting",
    "decor",
    [70, 3, 90],
    b.frame,
    onWall(120, { colors: { main: SAGE, second: BRASS } }),
  ),
  entry(
    "painting-large",
    "Schilderij groot",
    "Large painting",
    "decor",
    [120, 4, 80],
    b.frame,
    onWall(110, { colors: { main: "#7A8B99", second: DARK } }),
  ),
  entry(
    "poster",
    "Poster",
    "Poster",
    "decor",
    [50, 2, 70],
    b.frame,
    onWall(130, { colors: { main: CREAM, second: CHARCOAL } }),
  ),
  entry(
    "gallery-wall",
    "Fotowand",
    "Gallery wall",
    "decor",
    [150, 3, 100],
    b.frame,
    onWall(110, { colors: { main: GREIGE, second: BRASS } }),
  ),
  entry(
    "mirror-rect",
    "Spiegel",
    "Mirror",
    "decor",
    [60, 3, 90],
    b.mirror,
    onWall(110, { colors: { main: BRASS, second: BRASS } }),
  ),
  entry(
    "mirror-round",
    "Ronde spiegel",
    "Round mirror",
    "decor",
    [70, 3, 70],
    b.mirror,
    onWall(130, { params: { round: true }, colors: { main: BRASS, second: BRASS } }),
  ),
  entry("mirror-floor", "Passpiegel", "Floor mirror", "decor", [60, 4, 180], b.mirror, {
    layer: "decor",
    againstWall: true,
    colors: { main: OAK, second: OAK },
  }),
  entry(
    "tv-55",
    'Televisie 55"',
    'TV 55"',
    "decor",
    [123, 25, 78],
    b.tv,
    small({ colors: { main: CHARCOAL, second: CHARCOAL } }),
  ),
  entry(
    "tv-65-wall",
    'Televisie 65" aan muur',
    'TV 65" on wall',
    "decor",
    [145, 5, 84],
    b.tv,
    onWall(110, { params: { wall: true } }),
  ),
  entry("rug-160", "Vloerkleed 160x230", "Rug 160x230", "textiles", [230, 160, 1], b.rug, {
    layer: "decor",
    colors: { main: CREAM, second: GREIGE },
    palette: FABRICS,
  }),
  entry("rug-200", "Vloerkleed 200x300", "Rug 200x300", "textiles", [300, 200, 1], b.rug, {
    layer: "decor",
    colors: { main: "#C9B8A0", second: CREAM },
    palette: FABRICS,
  }),
  entry("rug-round", "Rond vloerkleed", "Round rug", "textiles", [160, 160, 1], b.rug, {
    shape: "round",
    layer: "decor",
    params: { round: true },
    colors: { main: SAGE, second: CREAM },
    palette: FABRICS,
  }),
  entry("runner", "Loper", "Runner", "textiles", [80, 250, 1], b.rug, {
    layer: "decor",
    colors: { main: "#B56B5A", second: CREAM },
  }),
  entry(
    "curtains",
    "Gordijnen",
    "Curtains",
    "textiles",
    [200, 10, 250],
    b.curtains,
    onWall(0, { colors: { main: LINEN, second: LINEN }, palette: FABRICS }),
  ),
  entry(
    "curtains-closed",
    "Gordijnen dicht",
    "Curtains closed",
    "textiles",
    [200, 10, 250],
    b.curtains,
    onWall(0, {
      params: { closed: true },
      colors: { main: LINEN, second: LINEN },
      palette: FABRICS,
    }),
  ),
  entry(
    "cushion",
    "Kussen",
    "Cushion",
    "textiles",
    [45, 15, 45],
    b.cushion,
    small({ palette: FABRICS, colors: { main: SAGE, second: SAGE } }),
  ),
  entry(
    "cushion-long",
    "Langwerpig kussen",
    "Lumbar cushion",
    "textiles",
    [60, 15, 30],
    b.cushion,
    small({ palette: FABRICS, colors: { main: "#B56B5A", second: "#B56B5A" } }),
  ),
  entry("floor-cushion", "Vloerkussen", "Floor cushion", "textiles", [60, 60, 15], b.cushion, {
    layer: "decor",
    palette: FABRICS,
    colors: { main: GREIGE, second: GREIGE },
  }),
  entry(
    "throw",
    "Plaid",
    "Throw",
    "textiles",
    [70, 40, 5],
    b.throwBlanket,
    small({ palette: FABRICS, colors: { main: "#C9B8A0", second: CREAM } }),
  ),
  entry(
    "blanket",
    "Deken",
    "Blanket",
    "textiles",
    [130, 60, 6],
    b.throwBlanket,
    small({ palette: FABRICS, colors: { main: SAGE, second: CREAM } }),
  ),
  entry(
    "bedspread",
    "Sprei",
    "Bedspread",
    "textiles",
    [160, 120, 3],
    b.throwBlanket,
    small({ palette: FABRICS, colors: { main: "#E3EAE2", second: SAGE } }),
  ),
  entry(
    "basket-plaid",
    "Mand met plaids",
    "Basket with throws",
    "textiles",
    [40, 40, 45],
    b.basket,
    {
      shape: "round",
      layer: "decor",
      params: { full: true },
      colors: { main: "#C9B08A", second: GREIGE },
    },
  ),
  entry("pouffe-knit", "Gebreide poef", "Knitted pouf", "textiles", [45, 45, 35], b.pouf, {
    shape: "round",
    layer: "decor",
    colors: { main: CREAM, second: CREAM },
  }),
  entry("room-divider", "Kamerscherm", "Room divider", "decor", [150, 4, 170], b.generic, {
    colors: { main: "#C9B08A", second: "#C9B08A" },
  }),
  entry("fireplace-screen", "Haardscherm", "Fireplace screen", "decor", [80, 25, 60], b.generic, {
    layer: "decor",
    colors: { main: CHARCOAL, second: CHARCOAL },
  }),
  entry(
    "globe",
    "Wereldbol",
    "Globe",
    "decor",
    [30, 30, 45],
    b.sculpture,
    small({ shape: "round", colors: { main: "#7A8B99", second: DARK } }),
  ),
  entry(
    "speaker",
    "Speaker",
    "Speaker",
    "decor",
    [20, 20, 30],
    b.generic,
    small({ colors: { main: CHARCOAL, second: CHARCOAL } }),
  ),
  entry(
    "record-player",
    "Platenspeler",
    "Record player",
    "decor",
    [45, 35, 12],
    b.generic,
    small({ colors: { main: OAK, second: OAK } }),
  ),
];

// --------------------------------------------------------------- lighting (21)
const light = (
  id: string,
  nl: string,
  en: string,
  size: [number, number, number],
  kind: string,
  extra: Opts = {},
) =>
  entry(id, nl, en, "lighting", size, b.lamp, {
    layer: "lighting",
    params: { kind },
    light: { color: "#FFE2B8", intensity: 0.7 },
    colors: { main: BRASS, second: CREAM },
    tags: ["lamp"],
    ...extra,
  });

const ceilingLight = (o: Opts = {}): Opts => ({
  mount: "wall",
  elevation: 0,
  shape: "round",
  ...o,
});

const lighting: CatalogEntry[] = [
  light("lamp-floor", "Staande lamp", "Floor lamp", [40, 40, 160], "floor", { shape: "round" }),
  light("lamp-floor-arc", "Booglamp", "Arc lamp", [180, 40, 200], "arc", {
    colors: { main: CHARCOAL, second: WHITE },
  }),
  light("lamp-floor-tripod", "Driepootlamp", "Tripod lamp", [55, 55, 155], "tripod", {
    shape: "round",
    colors: { main: OAK, second: LINEN },
  }),
  light("lamp-reading", "Leeslamp", "Reading lamp", [30, 30, 140], "floor", {
    shape: "round",
    colors: { main: CHARCOAL, second: CHARCOAL },
  }),
  light("lamp-table", "Tafellamp", "Table lamp", [30, 30, 50], "table", {
    shape: "round",
    mount: "stack",
    colors: { main: CREAM, second: LINEN },
  }),
  light("lamp-table-small", "Tafellampje", "Small table lamp", [20, 20, 35], "table", {
    shape: "round",
    mount: "stack",
    colors: { main: BRASS, second: CREAM },
  }),
  light("lamp-desk", "Bureaulamp", "Desk lamp", [20, 20, 45], "table", {
    shape: "round",
    mount: "stack",
    colors: { main: CHARCOAL, second: CHARCOAL },
  }),
  light(
    "lamp-pendant",
    "Hanglamp",
    "Pendant lamp",
    [45, 45, 80],
    "pendant",
    ceilingLight({ colors: { main: CHARCOAL, second: SAGE_DARK } }),
  ),
  light(
    "lamp-pendant-wide",
    "Hanglamp groot",
    "Large pendant",
    [70, 70, 90],
    "pendant",
    ceilingLight({ colors: { main: BRASS, second: CREAM } }),
  ),
  light(
    "lamp-pendant-rattan",
    "Hanglamp rotan",
    "Rattan pendant",
    [50, 50, 80],
    "pendant",
    ceilingLight({ colors: { main: "#C9B08A", second: "#C9B08A" } }),
  ),
  light("lamp-globe", "Bollamp", "Globe pendant", [30, 30, 70], "globe", ceilingLight()),
  light("lamp-ceiling", "Plafondlamp", "Ceiling light", [40, 40, 10], "ceiling", ceilingLight()),
  light(
    "lamp-ceiling-small",
    "Plafondlampje",
    "Small ceiling light",
    [25, 25, 8],
    "ceiling",
    ceilingLight(),
  ),
  light("lamp-spots", "Spotjes", "Spotlights", [90, 10, 15], "spots", {
    mount: "wall",
    elevation: 0,
    colors: { main: CHARCOAL, second: CHARCOAL },
  }),
  light(
    "chandelier",
    "Kroonluchter",
    "Chandelier",
    [80, 80, 80],
    "chandelier",
    ceilingLight({ light: { color: "#FFD9A0", intensity: 0.9 } }),
  ),
  light(
    "chandelier-small",
    "Kroonluchter klein",
    "Small chandelier",
    [55, 55, 60],
    "chandelier",
    ceilingLight(),
  ),
  light("lamp-wall", "Wandlamp", "Wall light", [20, 20, 30], "wall", {
    mount: "wall",
    elevation: 170,
  }),
  light("lamp-wall-pair", "Wandlamp (paar)", "Wall lights (pair)", [20, 20, 30], "wall", {
    mount: "wall",
    elevation: 160,
    colors: { main: CHARCOAL, second: CREAM },
  }),
  light("lamp-picture", "Schilderijlamp", "Picture light", [40, 15, 10], "wall", {
    mount: "wall",
    elevation: 200,
  }),
  light("led-strip", "Ledstrip", "LED strip", [150, 2, 1], "strip", {
    mount: "wall",
    elevation: 220,
    light: { color: "#FFE9C6", intensity: 0.4 },
  }),
  light("lamp-lantern", "Lantaarn", "Lantern", [20, 20, 35], "table", {
    shape: "round",
    mount: "stack",
    colors: { main: CHARCOAL, second: "#FFF4D6" },
  }),
];

// ------------------------------------------------------------------ life (12)
const lifeItem = (o: Opts = {}): Opts => ({ layer: "decor", life: true, ...o });

const life: CatalogEntry[] = [
  entry(
    "life-table-set-4",
    "Gedekte tafel (4)",
    "Laid table (4)",
    "life",
    [130, 80, 18],
    b.laidTable,
    lifeItem({ mount: "stack", params: { places: 4 }, colors: { main: WHITE, second: "#E0A33E" } }),
  ),
  entry(
    "life-table-set-6",
    "Gedekte tafel (6)",
    "Laid table (6)",
    "life",
    [170, 85, 18],
    b.laidTable,
    lifeItem({ mount: "stack", params: { places: 6 }, colors: { main: WHITE, second: "#E0A33E" } }),
  ),
  entry(
    "life-laundry",
    "Wasmand",
    "Laundry basket",
    "life",
    [45, 35, 55],
    b.basket,
    lifeItem({ params: { full: true }, colors: { main: "#C9B08A", second: WHITE } }),
  ),
  entry(
    "life-drying-rack",
    "Droogrek",
    "Drying rack",
    "life",
    [140, 55, 100],
    b.shelves,
    lifeItem({ params: { shelves: 2, open: true }, colors: { main: WHITE, second: WHITE } }),
  ),
  entry(
    "life-shoes",
    "Schoenen",
    "Shoes",
    "life",
    [30, 30, 12],
    b.shoes,
    lifeItem({ colors: { main: DARK, second: DARK } }),
  ),
  entry(
    "life-sneakers",
    "Sneakers",
    "Sneakers",
    "life",
    [32, 30, 12],
    b.shoes,
    lifeItem({ colors: { main: WHITE, second: WHITE } }),
  ),
  entry(
    "life-coats",
    "Jassen",
    "Coats",
    "life",
    [60, 20, 100],
    b.coats,
    lifeItem({ mount: "wall", elevation: 70, colors: { main: "#7A8B99", second: TERRACOTTA } }),
  ),
  entry(
    "life-toys",
    "Speelgoed",
    "Toys",
    "life",
    [70, 50, 30],
    b.toys,
    lifeItem({ colors: { main: "#E0A33E", second: "#7A8B99" } }),
  ),
  entry(
    "life-toy-box",
    "Speelgoedkist",
    "Toy box",
    "life",
    [70, 40, 45],
    b.basket,
    lifeItem({ params: { full: true }, colors: { main: WHITE, second: "#E0A33E" } }),
  ),
  entry(
    "life-mug",
    "Mok",
    "Mug",
    "life",
    [10, 8, 10],
    b.mug,
    lifeItem({ mount: "stack", shape: "round", colors: { main: WHITE, second: WHITE } }),
  ),
  entry(
    "life-newspaper",
    "Krant en tijdschriften",
    "Newspaper and magazines",
    "life",
    [40, 30, 3],
    b.books,
    lifeItem({
      mount: "stack",
      params: { count: 3, stack: true },
      colors: { main: CREAM, second: GREIGE },
    }),
  ),
  entry(
    "life-bag",
    "Tas",
    "Bag",
    "life",
    [40, 20, 35],
    b.generic,
    lifeItem({ colors: { main: TERRACOTTA, second: TERRACOTTA } }),
  ),
];

export const ENTRIES: readonly CatalogEntry[] = [
  ...seating,
  ...tables,
  ...bedroom,
  ...office,
  ...storage,
  ...kitchenBath,
  ...plants,
  ...decor,
  ...lighting,
  ...life,
];
